GET http://localhost:8080
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/hello
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/hello?param=123
Accept: */*
Cache-Control: no-cache

###

